---
name: Docs, templates, cookbook lint

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'docs/**'
      - 'templates/**'
      - 'cookbook/**'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run import check
      run: |
        # We should not encourage imports directly from main init file
        # Expect for hub
        git grep 'from langchain import' {docs,templates,cookbook} | grep -vE 'from langchain import (hub)' && exit 1 || exit 0

    - name: Run lint
      uses:
        ./.github/workflows/_lint.yml
      with:
        working-directory: .
      secrets: inherit

